set_property BITSTREAM.GENERAL.COMPRESS True [current_design]

set_property -dict { PACKAGE_PIN AB21 IOSTANDARD LVCMOS18 } [get_ports { clk_50mhz }];
create_clock -add -name sys_clk_pin -period 20.00 -waveform {0 10} [get_ports { clk_50mhz }];

set_property -dict { PACKAGE_PIN Y15 IOSTANDARD LVCMOS33 } [get_ports { rst_din }];

set_property -dict { PACKAGE_PIN AE13 IOSTANDARD LVCMOS33 } [get_ports { n64_ctrl_data[0] }];
set_property -dict { PACKAGE_PIN AD13 IOSTANDARD LVCMOS33 } [get_ports { n64_ctrl_data[1] }];
set_property -dict { PACKAGE_PIN AE15 IOSTANDARD LVCMOS33 } [get_ports { n64_ctrl_data[2] }];
set_property -dict { PACKAGE_PIN AD15 IOSTANDARD LVCMOS33 } [get_ports { n64_ctrl_data[3] }];

# -----------------------------------------------------------------------------
# HDMI TMDS via GTH transceivers (Quad 226) -> SN75DP159 redriver.
#
# The 4 GTH TX channels drive: hdmi_tx[2:0] (data lanes) + hdmi_clk (clock lane).
# MGT pin locations are fixed by the transceiver channel sites; assign the
# package pins that the board wires to the SN75DP159 inputs.
#
#   MGTHTX data lanes : N5 / L5 / J5   (channels X0Y8 / X0Y9 / X0Y10 -> bits 0/1/2)
#   MGTHTX clock lane : G5             (channel X0Y11               -> bit 3)
#   MGTREFCLK         : P7 / P6 (external PLL, 148.5 MHz), COMMON X0Y2, Quad 226
#
# The GTH TX pins are fixed by the channel placement (CHANNEL_ENABLE in the IP),
# so no PACKAGE_PIN is needed on the TX ports. Only the reference clock input
# needs a location. IOSTANDARD is not applicable to MGT ports.
# -----------------------------------------------------------------------------
set_property PACKAGE_PIN P7 [get_ports hdmi_mgtrefclk_p];
set_property PACKAGE_PIN P6 [get_ports hdmi_mgtrefclk_n];

# External 148.5 MHz transceiver reference clock (period 6.734 ns).
create_clock -name hdmi_mgtrefclk -period 6.734 [get_ports hdmi_mgtrefclk_p];
# (hdmi_tx_n[*] and hdmi_clk_n are inferred from the differential pairs above.)

# -----------------------------------------------------------------------------
# Clocking / CDC constraints.
#
# clk_pixel (148.5 MHz) is generated by an MMCM from txusrclk2 (37.125 MHz),
# both from the GT TX clock tree (frequency-locked 4:1). The symbol packer hands
# a 40-bit-per-lane word from the pixel domain to the txusrclk2 domain. The
# group boundary is anchored to a txusrclk2-derived strobe (load_toggle) so the
# handoff is phase-deterministic; the data is stable for ~4 pixel periods, so
# constrain it as a bounded datapath rather than a tight single-cycle path.
set_max_delay -datapath_only \
  -from [get_cells -hier -filter {NAME =~ *gth_tx*word_reg*}] \
  -to   [get_cells -hier -filter {NAME =~ *gth_tx*word_tx_reg*}] 6.700

# Group-boundary strobe crossing (txusrclk2 -> clk_pixel), a 1-bit synchronizer.
# Bound the source-to-first-sync-flop path; treat as a datapath crossing.
set_max_delay -datapath_only \
  -from [get_cells -hier -filter {NAME =~ *gth_tx*load_toggle_reg*}] \
  -to   [get_cells -hier -filter {NAME =~ *gth_tx*ld_sync_reg[0]*}] 6.700
